export type TranscriptSource = "player" | "dom" | "cache";

export interface TranscriptCue {
  start: number;
  end: number;
  text: string;
}

/** Identity of the caption track a transcript came from. Part of the transcript's cache identity. */
export interface CaptionTrackIdentity {
  /** Stable-ish handle derived from the track URL, used to detect track changes. */
  id: string;
  languageCode: string;
  languageName: string;
  /** `asr` = auto-generated by YouTube, `manual` = authored or community-contributed. */
  kind: "asr" | "manual";
  /** Set when YouTube machine-translated this track from another language. */
  translatedFrom?: string;
}

export interface VideoMetadata {
  id: string;
  title: string;
  url: string;
}

export interface TranscriptDocument {
  /** Content-addressed identity; see src/transcript/identity.ts. */
  transcriptId: string;
  video: VideoMetadata;
  track?: CaptionTrackIdentity;
  cues: TranscriptCue[];
  source: TranscriptSource;
  fetchedAt: number;
  /** Which parser produced these cues, so a parser fix invalidates caches. */
  parserVersion: number;
  /** Tracks offered by the page, so the panel can present a language selector. */
  availableTracks?: CaptionTrackIdentity[];
}

/**
 * Why an acquisition attempt ended. Replaces the old free-text `error` string, which collapsed
 * network failures, parse failures and genuinely caption-free videos into "No captions found".
 * The side panel maps these to distinct, actionable states.
 */
export type AcquisitionFailureReason =
  | "no-captions"
  /**
   * The caption endpoint answered 200 with an empty body.
   *
   * YouTube withholds timed-text from requests that do not carry the player's proof-of-origin
   * context. RecallTube does not attempt to reconstruct it; the legitimate path is YouTube's own
   * transcript panel, whose rendered rows the DOM adapter can read.
   */
  | "captions-withheld"
  | "track-unavailable"
  | "not-ready"
  /**
   * The side panel could not reach the content script in the target tab.
   *
   * Normal after the extension is reloaded or updated: tabs opened beforehand keep an orphaned
   * content script. Distinct from `not-ready`, which is about the YouTube player.
   */
  | "tab-not-connected"
  | "navigation-cancelled"
  | "network-error"
  | "parse-error"
  | "permission-denied"
  | "unsupported";

export interface AdapterDiagnostic {
  adapter: string;
  outcome: "ok" | "skipped" | "failed";
  detail: string;
  elapsedMs: number;
}

export type PageStatus = "idle" | "loading" | "ready" | "failed";

export interface PageSnapshot {
  status: PageStatus;
  videoId?: string;
  /** Incremented per navigation so stale results can be discarded. */
  generation: number;
  document?: TranscriptDocument;
  reason?: AcquisitionFailureReason;
  diagnostics?: AdapterDiagnostic[];
  /** Structural state used by diagnostics and the automatic native-panel fallback. */
  transcriptPanel?: "open" | "available" | "unavailable";
}

/**
 * Why a result surfaced. A result can carry several signals — an exact phrase that is also the
 * top semantic hit is more trustworthy than either alone. Drives the user-facing label; we never
 * show an invented probability.
 */
export type MatchSignal = "exact" | "boundary-exact" | "lexical" | "semantic" | "cross-language";

/** A matched span in original-text coordinates, addressed by cue. */
export interface CueHighlight {
  cueIndex: number;
  start: number;
  end: number;
}

export interface SearchResult {
  id: string;
  /** Seek target: the start of the strongest evidence, not the start of a broad chunk. */
  start: number;
  end: number;
  text: string;
  contextBefore?: string;
  contextAfter?: string;
  /** Fusion score. Comparable within one result set only; never rendered as a percentage. */
  score: number;
  signals: MatchSignal[];
  cueStartIndex: number;
  cueEndIndex: number;
  highlights: CueHighlight[];
  /** Short, factual reason this result appeared. */
  explanation?: string;
}

/** Granularity of a chunk: fine evidence spans, or the broader idea around them. */
export type ChunkScale = "fine" | "context";

export interface TranscriptChunk {
  id: string;
  scale: ChunkScale;
  start: number;
  end: number;
  text: string;
  cueStartIndex: number;
  cueEndIndex: number;
}
